/*
 * examples/cortex_m4/main.c
 *
 * On-target self-test for ARM Cortex-M4 (STM32F4 reference, easily ported to
 * STM32F3 / F7 / G4 / NXP Kinetis / Nordic nRF52840 / Microchip SAM4S).
 *
 * Wires the spiflash driver to:
 *   - STM32 HAL SPI master                 (SPI1 by default)
 *   - GPIO chip-select line                (PA4 by default)
 *   - HAL_Delay() blocking wait
 *   - HAL_UART_Transmit() to USART2        (115200 8N1) for the log
 *
 * Adapt the macros below to your board. The defaults match an
 * STM32F411-Discovery / Nucleo-F411RE with a Winbond W25Qxx wired to the
 * Arduino-style header:
 *
 *     CS    -> PA4
 *     SCK   -> PA5
 *     MISO  -> PA6
 *     MOSI  -> PA7
 *     VCC   -> 3.3V, GND -> GND
 *
 * Build by adding this file plus:
 *   - src/spiflash.c
 *   - src/spiflash_port.h
 *   - examples/common/spiflash_self_test.c
 * to your STM32CubeIDE / CMake / Make project, alongside the standard CMSIS
 * + STM32 HAL sources generated by STM32CubeMX.
 *
 * Define one of the byte-storage modes at compile time:
 *   -DSPIFLASH_BYTES_ONE_PER_WORD=1   (default; identical to upstream behavior)
 *
 * The packed-byte mode is C2000-only and not relevant on Cortex-M4.
 *
 * Open a serial terminal at 115200 8N1 to read the test report.
 */

/* CubeMX/HAL boilerplate. Replace the family include if you use a different
 * Cortex-M4 (e.g. "stm32f3xx_hal.h", "stm32g4xx_hal.h", "fsl_dspi.h", etc.).
 */
#include "stm32f4xx_hal.h"

#include <string.h>

#include "spiflash.h"
#include "spiflash_port.h"
#include "spiflash_self_test.h"

/* -------------------- BOARD-SPECIFIC SETTINGS -------------------- */

#ifndef SPIFLASH_EX_SPI_HANDLE
#define SPIFLASH_EX_SPI_HANDLE   hspi1
#endif

#ifndef SPIFLASH_EX_UART_HANDLE
#define SPIFLASH_EX_UART_HANDLE  huart2
#endif

#ifndef SPIFLASH_EX_CS_PORT
#define SPIFLASH_EX_CS_PORT      GPIOA
#endif
#ifndef SPIFLASH_EX_CS_PIN
#define SPIFLASH_EX_CS_PIN       GPIO_PIN_4
#endif

/* Flash defaults: Winbond W25Q64 (8 MiB). */
#ifndef SPIFLASH_EX_SIZE_BYTES
#define SPIFLASH_EX_SIZE_BYTES   (8u * 1024u * 1024u)
#endif
#ifndef SPIFLASH_EX_PAGE_SIZE
#define SPIFLASH_EX_PAGE_SIZE    256u
#endif
#ifndef SPIFLASH_EX_ADDR_SIZE
#define SPIFLASH_EX_ADDR_SIZE    3u
#endif
#ifndef SPIFLASH_EX_EXPECTED_JEDEC
#define SPIFLASH_EX_EXPECTED_JEDEC 0u
#endif

#ifndef SPIFLASH_EX_TEST_OFFSET
#define SPIFLASH_EX_TEST_OFFSET  0u
#endif
#ifndef SPIFLASH_EX_TEST_SIZE
#define SPIFLASH_EX_TEST_SIZE    1024u
#endif
#ifndef SPIFLASH_EX_DO_CHIP_ERASE
#define SPIFLASH_EX_DO_CHIP_ERASE 0u
#endif

/* These handles are normally created by STM32CubeMX in main.c / SPI.c. The
 * extern declarations here let this file compile without dragging in the
 * generated init code.
 */
extern SPI_HandleTypeDef  SPIFLASH_EX_SPI_HANDLE;
extern UART_HandleTypeDef SPIFLASH_EX_UART_HANDLE;

/* -------------------- LOGGING (UART) ----------------------------- */

static void log_str(const char *s) {
    HAL_UART_Transmit(&SPIFLASH_EX_UART_HANDLE,
                      (uint8_t *)s,
                      (uint16_t)strlen(s),
                      HAL_MAX_DELAY);
}

/* -------------------- HAL HOOKS ---------------------------------- */

static void cs_assert(void) {
    HAL_GPIO_WritePin(SPIFLASH_EX_CS_PORT, SPIFLASH_EX_CS_PIN, GPIO_PIN_RESET);
}
static void cs_deassert(void) {
    HAL_GPIO_WritePin(SPIFLASH_EX_CS_PORT, SPIFLASH_EX_CS_PIN, GPIO_PIN_SET);
}

static int hal_txrx(struct spiflash_s *spi, const uint8_t *tx_data,
                    uint32_t tx_len, uint8_t *rx_data, uint32_t rx_len) {
    (void)spi;
    HAL_StatusTypeDef st;
    if (tx_len > 0u && tx_data != NULL) {
        st = HAL_SPI_Transmit(&SPIFLASH_EX_SPI_HANDLE,
                              (uint8_t *)tx_data,
                              (uint16_t)tx_len,
                              HAL_MAX_DELAY);
        if (st != HAL_OK) return (int)st;
    }
    if (rx_len > 0u && rx_data != NULL) {
        st = HAL_SPI_Receive(&SPIFLASH_EX_SPI_HANDLE,
                             rx_data,
                             (uint16_t)rx_len,
                             HAL_MAX_DELAY);
        if (st != HAL_OK) return (int)st;
    }
    return SPIFLASH_OK;
}

static void hal_cs(struct spiflash_s *spi, uint8_t cs) {
    (void)spi;
    if (cs) cs_assert();
    else    cs_deassert();
}

static void hal_wait(struct spiflash_s *spi, uint32_t ms) {
    (void)spi;
    HAL_Delay(ms);
}

static const spiflash_hal_t HAL = {
    ._spiflash_spi_txrx = hal_txrx,
    ._spiflash_spi_cs   = hal_cs,
    ._spiflash_wait     = hal_wait,
};

/* -------------------- DRIVER STATE + BUFFERS --------------------- */

static spiflash_t s_spi;

static const spiflash_cmd_tbl_t s_cmds = SPIFLASH_CMD_TBL_STANDARD;

static const spiflash_config_t s_cfg = {
    .sz                = SPIFLASH_EX_SIZE_BYTES,
    .page_sz           = SPIFLASH_EX_PAGE_SIZE,
    .addr_sz           = SPIFLASH_EX_ADDR_SIZE,
    .addr_dummy_sz     = 0,
    .addr_endian       = SPIFLASH_ENDIANNESS_BIG,
    .sr_write_ms       = 10,
    .page_program_ms   = 2,
    .page_erase_ms     = 0,
    .block_erase_4_ms  = 100,
    .block_erase_8_ms  = 0,
    .block_erase_16_ms = 0,
    .block_erase_32_ms = 175,
    .block_erase_64_ms = 300,
    .chip_erase_ms     = 30000,
};

static spif_byte_t s_scratch_a[SPIF_OCTETS_TO_CELLS(SPIFLASH_EX_TEST_SIZE)];
static spif_byte_t s_scratch_b[SPIF_OCTETS_TO_CELLS(SPIFLASH_EX_TEST_SIZE)];

/* -------------------- ENTRY -------------------------------------- */

/* Call this from your CubeMX-generated main() after MX_GPIO_Init(),
 * MX_USART2_UART_Init() and MX_SPI1_Init() have completed.
 */
int spiflash_run_self_test(void) {
    cs_deassert();

    log_str("\r\nspiflash on-target self-test (Cortex-M4)\r\n");

    SPIFLASH_init(&s_spi, &s_cfg, &s_cmds, &HAL,
                  /*async_cb=*/NULL,
                  SPIFLASH_SYNCHRONOUS,
                  /*user_data=*/NULL);

    spif_self_test_ctx_t ctx = {
        .spi               = &s_spi,
        .log               = log_str,
        .step_hook         = NULL,
        .test_offset       = SPIFLASH_EX_TEST_OFFSET,
        .test_size         = SPIFLASH_EX_TEST_SIZE,
        .scratch_a         = s_scratch_a,
        .scratch_b         = s_scratch_b,
        .expected_jedec    = SPIFLASH_EX_EXPECTED_JEDEC,
        .enable_chip_erase = SPIFLASH_EX_DO_CHIP_ERASE,
    };

    int failures = spif_self_test_run(&ctx);
    log_str(failures == 0 ? "RESULT: PASS\r\n" : "RESULT: FAIL\r\n");
    return failures;
}
